### ISSUE TITLE
Embedding projector input

### ISSUE THREAD

**Issue by terry07** [Machine-Learning-Tokyo/DL_study_group#4]
Dear team,

thanks for your valuable tools.
I would like to ask some instructions about the files that are needed as input into the Embedding projector tool.
I transform a few bioBERT embeddings (768,) dimensionality but it crashes on the initial computation of PCA.

Could you also provide as the .tsv files of the existing examples?

Kind regards.

**Comment by suzana-ilic** [comment]
Hi Terry, you will have to ask the creators of the specific tools (in their GitHub repo), this is a collection of tools! Thank you!
